DROP TABLE IF EXISTS account;
CREATE TABLE account (
  _id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  currency TEXT NOT NULL,
  amount REAL NOT NULL DEFAULT '0'
);
INSERT INTO account VALUES (1,'Wallet','€',5);

DROP TABLE IF EXISTS move;
CREATE TABLE move (
  _id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  account_id INTEGER NOT NULL,
  tag_id INTEGER DEFAULT NULL,
  name TEXT NOT NULL,
  description TEXT DEFAULT NULL,
  amount REAL NOT NULL DEFAULT '0',
  added INTEGER DEFAULT NULL,
  FOREIGN KEY (account_id) REFERENCES account (_id) ON DELETE CASCADE,
  FOREIGN KEY (tag_id) REFERENCES tag (_id) ON DELETE SET NULL
);
INSERT INTO move VALUES (1,1,1,'Example Move','This is an example of an account move!',10,1413833899000),
(2,1,2,'Filters','Use the filter tab to filter moves by tag / date!',-5,1413833899000);

DROP TABLE IF EXISTS tag;
CREATE TABLE tag (
  _id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  color INTEGER NOT NULL,
  name TEXT NOT NULL
);
INSERT INTO tag VALUES (1,-65536,'Food'),(2,-16711936,'Party'),(3,-16776961,'Other');
